-- Database Schema for API Key Management System
-- Run this in Supabase SQL Editor

-- Create the api_keys table
CREATE TABLE public.api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    api_key TEXT NOT NULL,
    provider TEXT DEFAULT 'gemini' NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    usage_count BIGINT DEFAULT 0 NOT NULL,
    last_used_at TIMESTAMPTZ,
    error_log TEXT,
    remarks TEXT
);

-- Disable Row Level Security for this table
-- This allows the Edge Function to freely read/write
ALTER TABLE public.api_keys DISABLE ROW LEVEL SECURITY;

-- Insert your first API Key (replace with your actual key)
INSERT INTO public.api_keys (api_key, remarks)
VALUES 
    ('AIzaSyYourActualApiKeyHere', '我的第一个Gemini Key');

-- Optional: Create an index for better performance
CREATE INDEX idx_api_keys_active ON public.api_keys(is_active);
CREATE INDEX idx_api_keys_provider ON public.api_keys(provider);
CREATE INDEX idx_api_keys_last_used ON public.api_keys(last_used_at);
